---
- name: "Adjust outputs.conf permissions"
  file:
    path: "{{ splunk.home }}/etc/system/local/outputs.conf"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"

- name: "Enable forwarding to {{ forward_servers }}"
  ini_file:
    path: "{{ splunk.home }}/etc/system/local/outputs.conf"
    section: "tcpout:group1"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  with_items:
    - {key: "server", value: "{% for fwd in forward_servers %}{{ fwd }}:{{ splunk.s2s.port }}{{ ',' if not loop.last else '' }}{% endfor %}"}
    - {key: "clientCert", value: "{{ splunk.s2s.cert if splunk.s2s is defined and splunk.s2s.cert is defined else ''}}"}
    - {key: "sslPassword", value: "{{ splunk.s2s.password if splunk.s2s is defined and splunk.s2s.password is defined else ''}}"}
    - {key: "useClientSSLCompression", value: "{{ 'true' if splunk.s2s is defined and splunk.s2s.ssl is defined and splunk.s2s.ssl else '' }}"}
  when:
    - item.value | length > 0
  no_log: "{{ hide_password }}"
  register: forward_status

# Restart only when Splunk is running and when any of the above have changed
- include_tasks: trigger_restart.yml
  when: forward_status is changed or enable_ssl_forwarding is changed
